version: '3.8'

services:
  auth_service:
    extends:
      file: ./auth_service/docker-compose.yaml
      service: auth_service
    depends_on:
      - auth_db

  auth_db:
    extends:
      file: ./auth_service/docker-compose.yaml
      service: auth_db

  user_service:
    extends:
      file: ./user_service/docker-compose.yaml
      service: user_service
    depends_on:
      - user_db
      - auth_service

  user_db:
    extends:
      file: ./user_service/docker-compose.yaml
      service: user_db

volumes:
  auth_db_data:
  user_db_data: