
services:
  auth_service:
    extends:
      file: ./AuthService/docker-compose.yml
      service: auth_service
    networks:
      - microservices_network
      
  user_service:
    extends:
      file: ./UserService/docker-compose.yml
      service: user_service
    networks:
      - microservices_network
    depends_on:
      - auth_service

networks:
  microservices_network:
    driver: bridge