apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: trading-platform

build:
  artifacts:
    - image: auth-service
      context: ./AuthService
      docker:
        dockerfile: Dockerfile
    - image: user-service
      context: ./UserService
      docker:
        dockerfile: Dockerfile
    - image: watchlist-service
      context: ./Watchlist
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/auth-service.yaml
    - k8s/user-service.yaml
    - k8s/watchlist-service.yaml
    - k8s/secrets.yaml

portForward:
  - resourceType: service
    resourceName: auth-service
    port: 8001
    localPort: 8001
  - resourceType: service
    resourceName: user-service
    port: 8002
    localPort: 8002
  - resourceType: service
    resourceName: watchlist-service
    port: 8003
    localPort: 8003