
services:
  user_service:
    build: 
      context: .
    ports:
      - "${USER_SERVICE_PORT}:8002"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@user_db:5432/${USER_DB_NAME}
      - AUTH_SERVICE_URL=http://auth_service:8001
    depends_on:
      - user_db
    networks:
      - app_network
      
  user_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${USER_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

# Add test database service
  test_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=user_test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5437:5432"  # Different port from production
    networks:
      - app_network

networks:
  app_network:
    name: app_network    # Uses the same named network
    external: true      # Indicates this network already exists

volumes:
  user_db_data: {}