version: '3.8'

services:
  user_service:
    build: 
      context: ./user_service
    ports:
      - "${USER_SERVICE_PORT}:8003"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@user_db:5432/${USER_DB_NAME}
      - AUTH_SERVICE_URL=http://auth_service:8001
    depends_on:
      - user_db
      - auth_service
      
  user_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${USER_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "${USER_DB_PORT}:5432"
      
volumes:
  auth_db_data:
  user_db_data: