version: '3.8'

services:
  # Auth Service and DB
  auth_service:
    build: 
      context: ./auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:8001"
    environment:
      - DATABASE_URL=postgresql://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@auth_db:5432/${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - auth_db
      
  auth_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:5432"

volumes:
  user_db_data: