services:
  auth_service:
    build: 
      context: .
    ports:
      - "${AUTH_SERVICE_PORT}:8001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@auth_db:5432/${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - USER_SERVICE_URL=http://user_service:8002
    depends_on:
      - auth_db
      - test_db
    networks:
      - app_network
      
  auth_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app_network

  # Add test database service
  test_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=auth_test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5436:5432"  # Different port from production
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  postgres_data: {}