services:
  auth_service:
    build: 
      context: .
    ports:
      - "${AUTH_SERVICE_PORT}:8001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@auth_db:5432/${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - auth_db
      
  auth_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data    # Changed volume name here
    ports:
      - "${AUTH_DB_PORT}:5432"

volumes:
  postgres_data: {}    # Properly defined volume here