name: AuthService Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "AuthService/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "AuthService/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test_db:
        image: postgres:13
        env:
          POSTGRES_DB: auth_test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./AuthService
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio httpx

      - name: Run Tests
        working-directory: ./AuthService
        env:
          TESTING: "true"
          DATABASE_URL: postgresql://test_user:test_password@localhost:5436/auth_test_db
          SECRET_KEY: "test_secret_key"
          AUTH_SERVICE_PORT: 8001
          DB_USER: test_user
          DB_PASSWORD: test_password
          AUTH_DB_NAME: auth_test_db
        run: |
          pytest -v --cov=app
